# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  Tests:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup NodeJS 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Show NodeJS version    
        run: npm --version
      - name: Install Truffle
        run: npm install truffle -g
      - name: Install Truffle Dependencies
        run: npm install
      - name: Run Truffle Test with CI=true for Codechecks  
        run: CI=true truffle test
